"""product table-inda edilen deyisiklikler

Revision ID: 0c2e9e48fd5c
Revises: dd796eef2a69
Create Date: 2021-04-03 20:23:49.834606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2e9e48fd5c'
down_revision = 'dd796eef2a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))
        batch_op.drop_column('desc_content')
        batch_op.drop_column('desc_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc_title', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('desc_content', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
