"""multiple file upload-i yoxlamaq ucun edilen deyisiklikler

Revision ID: 10b9a360ec86
Revises: 0c2e9e48fd5c
Create Date: 2021-04-05 21:35:37.761747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b9a360ec86'
down_revision = '0c2e9e48fd5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finished_project_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['finished_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finished_project', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=100), nullable=True))

    op.drop_table('finished_project_image')
    # ### end Alembic commands ###
