"""ongoing_project table-na yeni sutun elave olunmasi

Revision ID: 38416da7c2e4
Revises: 
Create Date: 2021-03-30 18:36:59.896501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38416da7c2e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('on_going_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slugified_title', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('on_going_project', schema=None) as batch_op:
        batch_op.drop_column('slugified_title')

    # ### end Alembic commands ###
