"""on_going_project table-ina progress sutununun elave olunmasi

Revision ID: 5eb2b0b40633
Revises: 38416da7c2e4
Create Date: 2021-03-30 21:21:36.692423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb2b0b40633'
down_revision = '38416da7c2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('on_going_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('on_going_project', schema=None) as batch_op:
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
