"""sehvin duzeldilmesi 2

Revision ID: a0ad2a3ef7c1
Revises: 8904cd7d1e07
Create Date: 2021-04-12 22:17:08.181198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ad2a3ef7c1'
down_revision = '8904cd7d1e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.drop_column('e_mail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('e_mail', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
