"""multiple file upload-i yoxlamaq ucun edilen deyisiklikler 02

Revision ID: a12f3ad88d41
Revises: 10b9a360ec86
Create Date: 2021-04-05 21:44:16.143009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12f3ad88d41'
down_revision = '10b9a360ec86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_project_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=100), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_project_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
