"""contact_information table-inda edilen deyisiklikler

Revision ID: dd796eef2a69
Revises: 7f5fcf95d93e
Create Date: 2021-04-02 22:49:01.976841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd796eef2a69'
down_revision = '7f5fcf95d93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_location', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_information', schema=None) as batch_op:
        batch_op.drop_column('gm_location')

    # ### end Alembic commands ###
