"""partnerSlider-e name attributunun elave olunmasi

Revision ID: fe6fd1ec6cf0
Revises: 463d2aee4523
Create Date: 2021-03-24 21:56:50.537361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6fd1ec6cf0'
down_revision = '463d2aee4523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_slider', sa.Column('name', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_slider', 'name')
    # ### end Alembic commands ###
